name: test

on:
  push:
    branches:
      - test
      
env:
  MANAGE_DIR: simple-django/simplesite
    
jobs:
  my_job:
    name: Test Blog
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django django-bootstrap5
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: achen-dev/simple-django
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}
      - name: Run Tests
        run: |
          python manage.py test blog
        
