name: test

on:
  push:
    branches:
      - test
    
jobs:
  my_job:
    name: Test Blog
    runs-on: ubuntu-18.04
    env: 
      SECRET_KEY: non-prod-secret-12345678
      DEBUG: True
      
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django django-bootstrap5 requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Run Tests
        working-directory: ./simplesite
        run: |
          python manage.py test blog
        
